name: ProyectoLluvias
channels:
  - defaults
dependencies:
  - asttokens=3.0.0=py314haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py314h2b7f5b3_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - colorama=0.4.6=py314haa95532_0
  - comm=0.2.3=py314haa95532_0
  - debugpy=1.8.16=py314h885b0b7_1
  - decorator=5.2.1=py314haa95532_0
  - executing=2.2.1=py314haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py314h56ec5ee_0
  - ipython=9.7.0=py314haa95532_0
  - ipython_pygments_lexers=1.1.1=py314haa95532_0
  - jedi=0.19.2=py314haa95532_0
  - jupyter_client=8.6.3=py314haa95532_1
  - jupyter_core=5.9.1=py314haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libmpdec=4.0.0=h827c3e9_0
  - libsodium=1.0.20=h83e8143_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.2.1=py314haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py314h0b37514_0
  - mkl_fft=2.1.1=py314h281c9fe_0
  - mkl_random=1.3.0=py314hdbada53_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numexpr=2.14.1=py314h2592778_0
  - numpy=2.3.5=py314h0be4137_0
  - numpy-base=2.3.5=py314h96ad93d_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py314haa95532_1
  - pandas=2.3.3=py314hdbada53_1
  - parso=0.8.5=py314haa95532_0
  - pip=25.3=pyh0d26453_0
  - platformdirs=4.5.0=py314haa95532_0
  - prompt-toolkit=3.0.52=py314haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py314h02ab6af_1
  - pure_eval=0.2.3=py314haa95532_0
  - pygments=2.19.2=py314haa95532_0
  - python=3.14.2=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0post0=py314haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314haa95532_0
  - pywin32=311=py314h885b0b7_0
  - pyzmq=27.1.0=py314h7149c55_1
  - six=1.17.0=py314haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py314haa95532_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py314h827c3e9_0
  - traitlets=5.14.3=py314haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py314haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - branca==0.8.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - folium==0.20.0
      - fonttools==4.61.1
      - geopandas==1.1.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - pillow==12.0.0
      - pyogrio==0.12.1
      - pyparsing==3.2.5
      - pyproj==3.7.2
      - requests==2.32.5
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - shapely==2.1.2
      - threadpoolctl==3.6.0
      - urllib3==2.6.2
      - xyzservices==2025.11.0
prefix: C:\Users\nicoc\miniconda3\envs\ProyectoLluvias
