name: ProyectoLluvias
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - aom=3.9.1=he0c23c2_0
  - backports.zstd=1.2.0=py310h458dff3_0
  - blosc=1.21.6=h85f69ea_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py310hfff998d_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.7.3=h885b0b7_4
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=h8276f4a_0
  - fribidi=1.0.16=hfd05255_0
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.10.6=hd4c2148_0
  - geotiff=1.7.0=hbf7d8e7_4
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.4.0=h9e37d49_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h6470a55_1
  - libarchive=3.8.2=h6c023e8_0
  - libavif=1.3.0=he916da2_2
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgdal-core=3.11.4=h9cea349_0
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.53=h7351971_0
  - libspatialite=5.1.0=h6715bb4_2
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.9.4=hcfcfb64_0
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - minizip=4.0.6=hb638d1e_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_2
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py310h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - proj=9.3.1=he13c7e8_0
  - pyogrio=0.11.1=py310h2c68bc6_1
  - pyparsing=3.3.0=pyhcf101f3_0
  - pyproj=3.6.1=py310h05d47c7_5
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - rav1e=0.7.1=ha073cba_3
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=py310haa95532_0
  - shapely=2.1.2=py310h0c56243_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xerces-c=3.3.0=hac47afa_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - absl-py==2.3.1
      - alembic==1.17.2
      - astunparse==1.6.3
      - cachetools==6.2.4
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - colorlog==6.10.1
      - flatbuffers==25.12.19
      - gast==0.4.0
      - google-auth==2.45.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.3.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - llvmlite==0.46.0
      - mako==1.3.10
      - markdown==3.10
      - numba==0.63.1
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - optuna==4.6.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyyaml==6.0.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - seaborn==0.13.2
      - shap==0.49.1
      - slicer==0.0.8
      - sqlalchemy==2.0.45
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - tomli==2.3.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - werkzeug==3.1.4
      - wrapt==2.0.1
prefix: C:\Users\Nicolas\miniconda3\envs\ProyectoLluvias
